### ISSUE TITLE
Remove example directory

### ISSUE THREAD

**Issue by kl3ryk** [gore-gulp/plugin-less#2]
Remove `example` directory and instead of it put everything into readme.

**Comment by mcharytoniuk** [comment]
Why? Example is always useful.

**Comment by kl3ryk** [comment]
@mcharytoniuk indeed tests are necessary, but example is really simple so I think that it is not necessary here, but I understand that you want to provide consequence everywhere so I can agree with that.

**Comment by mcharytoniuk** [comment]
:thumbsup:
